---
title: "Bernie Marcus Breast Cancer Quality Control Metrics"
subtitle: "Preliminary Analysis From 'Good Quality' Data"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%B %d, %Y %H:%M')`"
knit: (function(inputFile, encoding) { 
      proj_name <- tools::file_path_sans_ext(basename(inputFile));
      out_dir <- paste0(proj_name, "_", Sys.Date());
      if(!file.exists(out_dir)) {   dir.create(out_dir) };
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                        out_dir, 
                        paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_", proj_name, ".html"))) 
                        })

output: 
  html_document:
    keep_md: yes
    df_print: paged
    toc: false
geometry: margin=0.5in
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
.main-container {
max-width: 1600px;
margin-left: auto;
margin-right: auto;
}
</style>
```

```{css, echo=FALSE}
h1, h2, h3, h4, h5, p {
text-align: center;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, cache = FALSE)
```

```{r libraries, message = FALSE, warning = FALSE}
library(rmarkdown)
library(tidyverse)
library(doParallel)
library(fcluster)
library(johnfuncs)
```

```{r user input}
## Full path to folder with sample files (excel or csv, or raw Thermo files)
## PASTE PATH IN BETWEEN INNER PARENTHASIS WITH QUOTES ON THE OUTSIDE -- NO NEED TO CHANGE BACKSLASHES TO FORWARD SLASHES
sample_dir <- gsub("\\\\", "/", r"(C:\Users\Jacob\Box\Eberlin_Lab_BCM\Projects\Breast MSPEN_Marcus Foundation\Data for Classifier)")

## Full path to feature list, otherwise NULL
#feature_file <- gsub("\\\\", "/", r"(C:\Users\Jacob\Box\Eberlin_Lab_BCM\People\MANOJ\Positive mode Analysis\List of MZ in positive mode.xlsx)")
feature_file <- NULL

## Full path to background peak list, otherwise NULL
#background_file <- gsub("\\\\", "/", r"(C:\Users\fjackobs\Desktop\DESI-data\Lung\for-power-calc\background.csv)")
background_file <- NULL

## ---------------------------------------------------------------------------

## Mass range to filter
mass_range <- c(100,1000)

## Peak Alignment Method: "clustering" or "featurelist"
peak_alignment_method <- "featurelist"

## If peak alignment method is "clustering":
clust_h <- 0.05 ## Height at which to cut dendrogram to determine clusters
clust_int_method  <-  "sumints" ## Handling of multiple intensities aggregating to one cluster centroid: "sumints" or "maxint"

## If peak alignment method is "featurelist":
ppm_error <- 5 ## Mass error tolerance of sample peaks to match to feature peaks

## Normalization Method: "tic", "maxpeak", "median", "medianlog", or "none"
normalization_method <- "tic" 

## ---------------------------------------------------------------------------

## Fraction of samples to use for training lasso model
train_fraction <- 0.7

## Randomization seed
seed <- 1234
```

```{r create directory for output files, include = FALSE}
proj_name <- tools::file_path_sans_ext(basename(rstudioapi::getSourceEditorContext()$path))

out_dir <- paste0(proj_name, "_", Sys.Date())

if(!file.exists(out_dir)) {   dir.create(out_dir) }

files_dir <- paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", proj_name, "_files")

if(!file.exists(file.path(out_dir,files_dir))) {   dir.create(file.path(out_dir,files_dir)) }
```