---
title: "Bernie Marcus Breast Signal-to-Noise Plots"
subtitle: "From 'Quality Control' Directory"
author: "`r Sys.info()[['user']]`"
date: "`r format(Sys.time(), '%B %d, %Y %H:%M')`"
knit: (function(inputFile, encoding) { 
      proj_name <- tools::file_path_sans_ext(basename(inputFile));
      out_dir <- paste0(proj_name, "_", Sys.Date());
      if(!file.exists(out_dir)) {   dir.create(out_dir) };
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                        out_dir, 
                        paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_", proj_name, ".html"))) 
                        })

output: 
  html_document:
    keep_md: yes
    df_print: paged
    toc: false
geometry: margin=0.5in
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
.main-container {
max-width: 1600px;
margin-left: auto;
margin-right: auto;
}
</style>
```

```{css, echo=FALSE}
h1,h2, h3, h4, h5, p {
text-align: center;
font-size: 20px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, cache = FALSE, results = "hold")
```

```{r libraries, message = FALSE, warning = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
library(ggpubr)

library(tidyverse)
library(ggthemes)
library(reshape2)
library(readxl)
library(rawrr)
library(sqldf)
library(readr)

library(stringr)
library(doParallel)
library(fcluster)
library(johnfuncs)
```

```{r user input}
## Full path to folder with sample files (excel or csv, or raw Thermo files)
## PASTE PATH IN BETWEEN INNER PARENTHESIS WITH QUOTES ON THE OUTSIDE -- NO NEED TO CHANGE BACKSLASHES TO FORWARD SLASHES
sample_dir <- gsub("\\\\", "/", r"(C:\Users\Jacob\Box\Eberlin_Lab_BCM\Projects\Breast MSPEN_Marcus Foundation\Quality Control\Lab Data)")
#sample_dir <- gsub("\\\\", "/", r"(/Users/jacobmardick/Library/CloudStorage/Box-Box/Eberlin_Lab_BCM/Projects/Breast MSPEN_Marcus Foundation/Data for Classifier)")

## Full path to feature list, otherwise NULL
#feature_file <- gsub("\\\\", "/", r"(C:\Users\Jacob\Documents\Breast-BernieMarcus\20250218_QC-metric-feature-list.xlsx)")
feature_file <- NULL

## Full path to background peak list, otherwise NULL
## TODO: add functionality for xlsx background files
#background_file <- gsub("\\\\", "/", r"(C:\Users\fjackobs\BACKGROUND_FILE.csv)")
background_file <- NULL

## ---------------------------------------------------------------------------

## Scan numbers to import when using raw Thermo files
scans <- 50:500 ## number of scans to extract from each raw file

## Mass range to filter
mass_range <- c(100,1000)

## Peak Alignment Method: "clustering", "binning", or "featurelist"
peak_alignment_method <- "clustering" ## Only use clustering method for this analysis. Need to add back in binning or featurelist code if those methods are desired

## If peak alignment method is "clustering":
clust_h <- 0.05 ## Height at which to cut dendrogram to determine clusters

## If peak alignment method is "featurelist":
ppm_error <- 5 ## Mass error tolerance of sample peaks to match to feature peaks

## Normalization Method: "tic", "maxpeak", "median", "medianlog", or "none"
normalization_method <- "none"

## Target m/z values of interest for QC metrics
target_mz <- c(145.05, 175.03, 215.03, 303.23, 327.23, 750.54, 810.53, 885.55)
```

```{r create directory for output files, include = FALSE}
proj_name <- tools::file_path_sans_ext(basename(rstudioapi::getSourceEditorContext()$path))

out_dir <- paste0(proj_name, "_", Sys.Date())

if(!file.exists(out_dir)) {   dir.create(out_dir) }

files_dir <- paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", proj_name, "_files")

if(!file.exists(file.path(out_dir,files_dir))) {   dir.create(file.path(out_dir,files_dir)) }
```

```{r classes}
## fixed objects for exporting to parallel computing
fixed_objects <- list(scans = scans, mass_range = mass_range)

classes_path <- gsub(file.path(sample_dir, "/"), "", list.dirs(sample_dir)[c(-1)], fixed=TRUE)

classes <- strsplit(classes_path, "/")
classes <- classes[lapply(classes,length)==2]

classes_path <- lapply(classes, function(x) paste(x, collapse = '/'))

classes <- sapply(classes, `[`, 2)
classes <- unique(classes)
classes <- classes[!is.na(classes)]

names(classes_path) <- classes

## check file extension
sample_file_ext <- unique(unlist(
  lapply(classes_path, function(x) 
    tools::file_ext(list.files(file.path(sample_dir, "/",x,"/"))))))[1]
```

```{r file and sample names}
## file names
file_name_list <- lapply(classes_path, function(x) 
  list.files(path = file.path(sample_dir,x), pattern = paste0("*.", sample_file_ext), full.names = TRUE, recursive = TRUE))

## Ensure patient ordering is consistent across different OSes.
file_name_list <- lapply(file_name_list, sort)

## sample names
sample_names_list <- lapply(file_name_list, function(x) tools::file_path_sans_ext(basename(x)))
sample_names <- unlist(sample_names_list)
sample_names_df <- purrr::map_df(sample_names_list, ~as.data.frame(.x), .id="id")
colnames(sample_names_df) <- c("class", "sample_name")

classes <- names(file_name_list)
```

```{r csv data}
if (sample_file_ext == "csv") {
  
  process_csv <- function(file_name_list, fixed_objects) {
    cl <- makeCluster(detectCores() - 1)  # Use one less than available cores
    registerDoParallel(cl)
    
    clusterEvalQ(cl, {
      library(dplyr)
      library(purrr)
      library(readr)
    })
    
    result <- foreach(i = seq_along(file_name_list), .packages = c('dplyr', 'purrr', 'readr')) %:% 
      foreach(j = seq_along(file_name_list[[i]])) %dopar% {
        
        file_path <- file_name_list[[i]][[j]]
        
        ## Read CSV file
        spectrum <- read_csv(file_path, col_names = c("mass", "intensity", "SNR"), skip = 6, show_col_types = FALSE)

        ## Ensure mass is numeric and rounded
        spectrum$mass <- as.numeric(spectrum$mass)
        spectrum$mass <- round(spectrum$mass, 3)

        ## Filter based on mass range
        spectrum <- spectrum %>%
          filter(mass >= fixed_objects$mass_range[1] & mass <= fixed_objects$mass_range[2])
        
        ## Separate into spectra (mass + intensity) and SNR (mass + SNR)
        spectra_df <- spectrum %>% select(mass, intensity)
        snr_df <- spectrum %>% select(mass, SNR)

        ## Return structured list with both
        return(list(spectra = spectra_df, snr = snr_df))
      }
    
    stopCluster(cl)
    
    ## Remove NULL values (if any)
    result <- lapply(result, function(class_list) {
      Filter(Negate(is.null), class_list)
    })
    
    return(result)
  }

  ## Run CSV processing
  processed_data <- process_csv(file_name_list, fixed_objects)

  ## Extract spectra and SNR separately
  spectra_list <- lapply(processed_data, function(class_list) lapply(class_list, function(sample) sample$spectra))
  snr_list <- lapply(processed_data, function(class_list) lapply(class_list, function(sample) sample$snr))

  ## Assign sample names properly
  spectra_list <- lapply(seq_along(spectra_list), \(i) setNames(spectra_list[[i]], sample_names_list[[i]]))
  names(spectra_list) <- classes
  
  snr_list <- lapply(seq_along(snr_list), \(i) setNames(snr_list[[i]], sample_names_list[[i]]))
  names(snr_list) <- classes
}
```

``` {r peak alignment clustering}
## If peak alignment method is clustering
if (peak_alignment_method == "clustering") {
  
  clust_int_method  <-  "sumints" ## Handling of multiple intensities aggregating to one cluster centroid: "sumints" or "maxint"
  
  ## If background peak list: add background peaks to clustering
  if (!is.null(background_file)) {
    bg_mz <- unlist(read.csv(background_file, header = FALSE))
    
    sample_mz <- sort(unlist(
      lapply(spectra_list, function(y)
        lapply(y, function(x)
          round(x$mass, 3)))))
    
    all_mz <- c(bg_mz, sample_mz)
    names(all_mz) <- all_mz
    
  } else { ## If no background peak list
    all_mz <- sort(unlist(
      lapply(spectra_list, function(y)
        lapply(y, function(x)
          round(x$mass, 3)))))
    
    names(all_mz) <- all_mz
  }
  
  ## Cluster peaks into centroids
  tree <- fcluster(all_mz)
  clust_mz <- fcutree(all_mz, tree, h=clust_h)
  clustMZ <- sort(clust_mz$cen)
  
  ## Match cluster centroids to sample peaks
  clusterMatrixList <- lapply(spectra_list, function(x, y, z, w) 
    get_cluster_matrix(x, y, z, w), y=clustMZ, z = clust_h, w = clust_int_method)
  
  ## Match SNRs to sample peaks to match clusterMatrixList
  snrClusterMatrixList <- lapply(snr_list, function(x, y, z, w) 
    get_cluster_matrix(x, y, z, w), y=clustMZ, z = clust_h, w = "maxint")
  
  preprocList <- lapply(clusterMatrixList, function(x) as.matrix(get_data_matrix_clustering(x)))
  
  ## Perform the same for SNR
  preprocSNRList <- lapply(snrClusterMatrixList, function(x) as.matrix(get_data_matrix_clustering(x)))
  
  aligned_spectra <- do.call(rbind, preprocList)
  
  colnames(aligned_spectra) <- clustMZ
  rownames(aligned_spectra) <- sample_names
  
  ## FILTER #3: REMOVE RARE/UNCOMMON PEAKS PRESENT < 10% SAMPLES
  #mz_count_filter <- colSums(aligned_spectra != 0) > as.integer(nrow(aligned_spectra)*0.10)
  #aligned_spectra <- aligned_spectra[, mz_count_filter]
  
  #filtered_mz <- clustMZ[mz_count_filter]
  
  ## FILTER #4: REMOVE BACKGROUND PEAKS (IF BACKGROUND FILE PRESENT)
  #if (!is.null(background_file)) {
    
    ## match bg_mz to cluster centroid
    #temp_a <- data.frame(cluster_id = clust_mz$cluster_index,
    #                     all_mz = all_mz)
    
    #temp_b <- data.frame(clust_centroid = clust_mz$centroid, 
    #                     cluster_id = unique(clust_mz$cluster_index)[order(unique(clust_mz$cluster_index))])
    
    #temp_c <- merge(temp_a, temp_b, by = "cluster_id")
    
    #bg_centroids <- unique(temp_c[temp_c$all_mz %in% bg_mz, ])
    
    ## Remove peaks from aligned_spectra that are in bg_mz_centroid
    ## CHANGE THIS SO ITS NOT LOOKING IN COLUMN NAMES BECAUSE THOSE ARE CHARACTERS AND NOT NUMERIC WHICH MESSES STUFF UP
    #aligned_spectra <- aligned_spectra[, !(colnames(aligned_spectra) %in% bg_centroids$clust_centroid)]
    
    #filtered_mz <- as.numeric(colnames(aligned_spectra))
  #}
  
  ## which peaks make up a cluster
  ## Cluster indexes
  cluster_index <- data.frame(clust_mz$cluster_index)
  colnames(cluster_index) <- c("cluster")
  
  ## Attach cluster_index and all_mz
  mz_cluster_index <- cbind(cluster_index, all_mz)
  
  ## Average m/z values in same cluster to calculate centroid m/z value
  mz_centroid <- data.frame(cluster = seq(1:length(clust_mz$centroid)), centroid = clust_mz$centroid)
  
  ## Join centroids to original mz values
  mz_cluster_index <- merge(mz_cluster_index,
                            mz_centroid,
                            by = "cluster",
                            all = TRUE)
  
  colnames(mz_cluster_index) <- c("cluster","mass","centroid")
  
  ## Remove duplicate rows of same cluster, mz, and centroid
  mz_cluster_index <- mz_cluster_index[!duplicated(mz_cluster_index), ]
  
  ## min and max for each centroid
  centroid_min_max <- mz_cluster_index %>%
    group_by(cluster) %>%
    summarise(
      centroid = first(centroid),
      min_mass = min(mass),
      max_mass = max(mass)
    )
  
  ## only keep filtered_mz in min_max_clusters df
  #centroid_min_max <- centroid_min_max[which(centroid_min_max$centroid %in% filtered_mz), ]
}
```

```{r normalization}
xall <- normalize_pixel(aligned_spectra, normalization_method)
```

```{r SNR matrix}
## This is the same with the creation of xall, except no normalization since SNR
xall_snr <- (do.call(rbind, preprocSNRList))
colnames(xall_snr) <- clustMZ
rownames(xall_snr) <- sample_names
```

```{r yall}
## create yall object 
yall <- factor(sample_names_df$class, levels = c(classes), labels = classes)
```

```{r extract mz}
## Convert xall to data frame
xall_df <- as.data.frame(xall)
xall_df$Sample <- rownames(xall_df)

## Convert to long format for ggplot
xall_long <- xall_df |> 
  pivot_longer(cols = -Sample, names_to = "mz", values_to = "Intensity") |> 
  mutate(mz = as.numeric(mz))

tolerance <- 0.05

## Extract desired peaks
xall_filtered <- xall_long |> 
  group_by(Sample) |> 
  reframe(
    target_mz = rep(target_mz, each = 1),
    closest_mz = map_dbl(target_mz, function(t) {
       nearest_mz <- mz[which.min(abs(mz - t))]
       if (abs(nearest_mz - t) <= tolerance) return(nearest_mz) else return(NA_real_)  # Ensure NA for out-of-tolerance matches
    }),
    Intensity = map_dbl(target_mz, function(t) {
      nearest_index <- which.min(abs(mz - t))
      if (abs(mz[nearest_index] - t) <= tolerance) return(Intensity[nearest_index]) else return(NA_real_)
    })
  ) |> 
  filter(!is.na(closest_mz))

## Include class label from sample_names_df and make as factor
xall_filtered <- xall_filtered |> 
  left_join(sample_names_df, by = c("Sample" = "sample_name"))
xall_filtered$class <- as.factor(xall_filtered$class)

## Unique m/z values
unique_mz <- unique(xall_filtered$target_mz)
```

``` {r extract SNR}
## Convert xall to data frame
xall_snr_df <- as.data.frame(xall_snr)
xall_snr_df$Sample <- rownames(xall_snr_df)

## Convert to long format for ggplot
xall_snr_long <- xall_snr_df |> 
  pivot_longer(cols = -Sample, names_to = "mz", values_to = "SNR") |> 
  mutate(mz = as.numeric(mz))

## Extract desired peaks
xall_snr_filtered <- xall_snr_long |> 
  group_by(Sample) |> 
  reframe(
    target_mz = rep(target_mz, each = 1),
    closest_mz = map_dbl(target_mz, function(t) {
       nearest_mz <- mz[which.min(abs(mz - t))]
       if (abs(nearest_mz - t) <= tolerance) return(nearest_mz) else return(NA_real_)  # Ensure NA for out-of-tolerance matches
    }),
    SNR = map_dbl(target_mz, function(t) {
      nearest_index <- which.min(abs(mz - t))
      if (abs(mz[nearest_index] - t) <= tolerance) return(SNR[nearest_index]) else return(NA_real_)
    })
  ) |> 
  filter(!is.na(closest_mz))

## Include class label from sample_names_df and make as factor
xall_snr_filtered <- xall_snr_filtered |> 
  left_join(sample_names_df, by = c("Sample" = "sample_name"))
xall_snr_filtered$class <- as.factor(xall_snr_filtered$class)

## Unique m/z values
unique_snr_mz <- unique(xall_snr_filtered$target_mz)
```

```{r intensity plots}
## Colorblind-friendly palette
colorblind_palette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")

## Separate plots of Sample vs Intensity for each target m/z value
for (mz in unique_mz) {
  xall_subset <- xall_filtered |> 
    filter(target_mz == mz) |> 
    mutate(
      group = ifelse(grepl("^Good", class), "Good", "Poor"),
      class = factor(class, levels = c("Good-Cancer", "Good-Normal", "Poor-Cancer", "Poor-Normal"))
    ) |> 
    arrange(group, class, Sample)
  
  ## Set Sample as factor to preserve order in plot  
  xall_subset$Sample <- factor(xall_subset$Sample, levels = xall_subset$Sample)  ## Ensure Sample is a factor
  
  ## Classification for plot divider
  divider_position <- sum(xall_subset$group == "Good") + 0.5
  
  ## Average intensities per group
  avg_good <- mean(xall_subset$Intensity[xall_subset$group == "Good"], na.rm = TRUE)
  avg_poor <- mean(xall_subset$Intensity[xall_subset$group == "Poor"], na.rm = TRUE)
  y_max <- max(xall_subset$Intensity, na.rm = TRUE) * 1.1 
  good_range <- which(xall_subset$group == "Good")
  poor_range <- which(xall_subset$group == "Poor")

  ## Generate plot
  plot <- ggplot(xall_subset, aes(x = Sample, y = Intensity)) +
    
    ## Background shading
    annotate("rect", xmin = 0, xmax = divider_position - 0.5, ymin = -Inf, ymax = Inf, fill = "#56B4E9", alpha = 0.3) +
    annotate("rect", xmin = divider_position, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "#E69F00", alpha = 0.3) +
    
    ## Horizontal line for average good intensity
    annotate("segment",
         x = as.numeric(good_range[1]),
         xend = as.numeric(good_range[length(good_range)]),
         y = avg_good, yend = avg_good,
         color = "#0072B2", linewidth = 1) +
annotate("segment",
         x = as.numeric(poor_range[1]),
         xend = as.numeric(poor_range[length(poor_range)]),
         y = avg_poor, yend = avg_poor,
         color = "#D55E00", linewidth = 1) +
    
    ## Label average intensity lines
    annotate("text", x = divider_position / 2, y = y_max * 0.95, label = paste0("Avg Good", " ", toupper(normalization_method), " ", "Intensity:", round(avg_good, 5)), color = "#0072B2", size = 4) +
    annotate("text", x = divider_position + (nrow(xall_subset) - divider_position) / 2, y = y_max * 0.95, label = paste0("Avg Poor", " ", toupper(normalization_method), " ", "Intensity:", round(avg_poor, 5)), color = "#D55E00", size = 4) +
    
    ## Scatter points with colorblind-friendly colors
    geom_point(color = colorblind_palette[1], size = 2, alpha = 0.7) +
    geom_line(aes(group = 1), color = "gray") +

    ## Improve theme
    theme_minimal() +
    
    ## Labels
    labs(title = paste("Intensities for m/z", mz), x = "Sample", y = paste0(toupper(normalization_method), " ", "Intensity")) +
    scale_x_discrete() +  ## Ensure sample is treated as discrete
    theme(plot.margin = margin(10, 50, 10, 50, "pt"),
          axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
          plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
          axis.title.x = element_text(size = 14, face = "bold"),
          axis.title.y = element_text(size = 14, face = "bold"),
          axis.text.y = element_text(size = 12))

  print(plot)
  ggsave(filename = file.path(out_dir, files_dir, paste0(proj_name, "_mz_", mz, "_scatter-plot.png")), 
         plot = plot, width = 16, height = 6, dpi = 300)  
}
```

``` {r snr plots}
## Separate plots of Sample vs SNR for each target m/z value
## Loop through each m/z and generate a separate plot
for (mz in unique_mz) {
  ## Filter data for this specific m/z
  xall_snr_subset <- xall_snr_filtered |> 
    filter(target_mz == mz) |>
    mutate(
      group = ifelse(grepl("^Good", class), "Good", "Poor"),
      class = factor(class, levels = c("Good-Cancer", "Good-Normal", "Poor-Cancer", "Poor-Normal"))
    ) |>
    arrange(group, class, Sample) 
  
  ## Preserve Sample Order
  xall_snr_subset$Sample <- factor(xall_snr_subset$Sample, levels = xall_snr_subset$Sample)
  
  ## Position to draw divider between Normal and Cancer in Plot
  divider_position <- sum(xall_snr_subset$group == "Good") + 0.5
  
  ## Calculate average SNR for this m/z
  avg_good <- mean(xall_snr_subset$SNR[xall_snr_subset$group == "Good"], na.rm = TRUE)
  avg_poor <- mean(xall_snr_subset$SNR[xall_snr_subset$group == "Poor"], na.rm = TRUE)
  good_range <- which(xall_snr_subset$group == "Good")
  poor_range <- which(xall_snr_subset$group == "Poor")
  
  ## Define y_max to ensure labels fit inside the plot
  y_max <- max(xall_snr_subset$SNR, na.rm = TRUE) * 1.1
  
  ## Generate plot
  plot <- ggplot(xall_snr_subset, aes(x = Sample, y = SNR)) +
    annotate("rect", xmin = 0, xmax = divider_position - 0.5, ymin = -Inf, ymax = Inf,
             fill = "#56B4E9", alpha = 0.3) +
    annotate("rect", xmin = divider_position, xmax = Inf, ymin = -Inf, ymax = Inf,
             fill = "#E69F00", alpha = 0.3) +
    
    # Average segments for each group
    annotate("segment",
             x = as.numeric(good_range[1]),
             xend = as.numeric(good_range[length(good_range)]),
             y = avg_good, yend = avg_good,
             color = "#0072B2", linewidth = 1) +
    annotate("segment",
             x = as.numeric(poor_range[1]),
             xend = as.numeric(poor_range[length(poor_range)]),
             y = avg_poor, yend = avg_poor,
             color = "#D55E00", linewidth = 1) +

    # Average labels
    annotate("text", x = divider_position / 2, y = y_max * 0.95, 
             label = paste0("Avg Good SNR: ", round(avg_good, 2)),
             color = "#0072B2", size = 4) +
    annotate("text", x = divider_position + (nrow(xall_snr_subset) - divider_position) / 2, 
             y = y_max * 0.95, 
             label = paste0("Avg Poor SNR: ", round(avg_poor, 2)), 
             color = "#D55E00", size = 4) +

    # Points and line
    geom_point(color = colorblind_palette[1], size = 2, alpha = 0.7) +
    geom_line(aes(group = 1), color = "gray") +

    theme_minimal() +
    labs(
      title = paste("Signal-to-Noise Ratios for m/z", mz),
      x = "Sample",
      y = "Signal-to-Noise Ratio"
    ) +
    scale_x_discrete() +
    theme(
      plot.margin = margin(10, 50, 10, 50, "pt"),
      axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
      plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
      axis.title.x = element_text(size = 14, face = "bold"),
      axis.title.y = element_text(size = 14, face = "bold"),
      axis.text.y = element_text(size = 12)
    )

  print(plot)
  
  ## Save each plot with a larger width
  plot_filename <- paste0(proj_name, "_mz_", mz, "_SNR_scatter-plot.png")
  ggsave(filename = file.path(out_dir, files_dir, plot_filename), 
         plot = plot, 
         width = 16, height = 6, dpi = 300)  ## Increased width to improve readability
}
```

<br>

#### **Preprocessing and Statistical Model Settings**

```{r chunk3, fig.align = "center"}
if (peak_alignment_method == "clustering") {
  cluster_bin_size <- c("Cluster Height:", clust_h)
} else if (peak_alignment_method == "binning") {
  cluster_bin_size <- c("Bin Size:", "0.01")
} else if (peak_alignment_method == "featurelist") {
  cluster_bin_size <- c("Feature Mass Error (ppm):", ppm_error)
}

if (is.null(background_file)) {
  bg_exclusion <- "no"
} else if (!is.null(background_file)) {
  bg_exclusion <- "yes"
}

settings_df <- rbind(c("Mass Range (m/z):", paste0(mass_range[1], " - ", mass_range[2])),
                     c("Peak Alignment Method:", peak_alignment_method),
                     cluster_bin_size,
                     c("Background Peak Exclusion:", bg_exclusion),
                     c("Normalization Method:", normalization_method))

kable(settings_df,
      row.names = FALSE,
      align = "l",
      format = "html",
      escape = FALSE)%>%
  column_spec(1:2, width = "3in")%>% 
  kable_styling(full_width = FALSE, 
                font_size = 14)
```

```{r R data, include = FALSE}
save(list = ls(), 
     file=file.path(out_dir, files_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", proj_name,"_preprocessed.RData")))
```

<br>

#### **Session Info**

```{r}
sessionInfo()
```